# Production override for docker-compose
# Usage: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up

version: '3.8'

services:
  python-api:
    environment:
      - CORS_ORIGINS=${CORS_ORIGINS:-https://careergenai.com}
      - FRONTEND_BASE_URL=${FRONTEND_BASE_URL:-https://careergenai.com}
      - PYTHONUNBUFFERED=1
      - WORKERS=4
    command: ["uvicorn", "chatbot:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "4"]
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

  node-backend:
    environment:
      - NODE_ENV=production
      # - PYTHON_API_URL=http://python-api:8000
      - PYTHON_API_URL=https://careergen.onrender.com
      - PORT=3000
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.25'
        reservations:
          memory: 256M
          cpus: '0.1'